name: Testes Unitários

on:
  push:
    branches:
      - main
      - discord-integration
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7' 
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest "httpx[http2]" fastapi

      - name: Executar os testes
        run: |
          pytest